const AT = {
  SET_SIGN_UP_SUCCESS: 'SET_SIGN_UP_SUCCESS',
  SET_SIGN_IN_SUCCESS: 'SET_SIGN_IN_SUCCESS',
  GET_ALL_TENNANTS_SUCCESS: 'GET_ALL_TENNANTS_SUCCESS',
  ADD_NEW_TENNANT_SUCCESS: 'ADD_NEW_TENNANT_SUCCESS',
  UPDATE_TENNANT_SUCCESS: 'UPDATE_TENNANT_SUCCESS',
  DELETE_TENNANT_SUCCESS: 'DELETE_TENNANT_SUCCESS',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  SET_TO_LOCAL_STORAGE_SUCCESS: 'SET_TO_LOCAL_STORAGE_SUCCESS',
  SET_USER_DATA_SUCCESS: 'SET_USER_DATA_SUCCESS'
};

export default AT;
